(#332) LayerSurfaceLayoutTest includes a test for a -1 exclusion zone
canonical/wlcs pull request #333
Opened 2024-03-13 15:12 UTC by mattkae

fixes #332 

Implemented a test for `zwlr_layer_surface_v1_set_exclusive_zone(-1)`, which means that the surface should ignore all exclusion zones (e.g. a background)

2024-03-14 06:44 UTC, RAOF requested changes
I'm a bit confused at what this test is doing, and I think it's because the test isn't testing what you think it is.

I think it would be more obvious what it's doing if either:
* You set up the exclusive surfaces first, then set up the `exclusive=-1` surface and checked its position, or
* You set up the `exclusive=-1` surface, checked its position, *then* set up the exclusive surfaces and asserted that no reconfiguration occured.

(It's possible that this is more usefully *two* tests)

2024-03-14 06:44 UTC, RAOF commented on tests/wlr_layer_shell_v1.cpp
> +    surface.attach_visible_buffer(expected_placement.size.width.as_int(), expected_placement.size.height.as_int());
Additionally, you're never `commit`ting this buffer, so it's not going to do anything?

2024-03-14 06:44 UTC, RAOF commented on tests/wlr_layer_shell_v1.cpp
> +    auto const expected_placement = layout.placement_rect(non_exlusive_zone);
Why are we naming this differently? `expected_placement == initial_rect`

2024-03-14 18:08 UTC, mattkae commented
> I'm a bit confused at what this test is doing, and I think it's because the test isn't testing what you think it is.

I am attempting to test that ignoring exclusive zones while you are a fullscreened surface gives you the whole output, regardless of there being attached surfaces with exclusive zones defined.

> I think it would be more obvious what it's doing if either:
> 
>     * You set up the exclusive surfaces first, then set up the `exclusive=-1` surface and checked its position, or
> 
>     * You set up the `exclusive=-1` surface, checked its position, _then_ set up the exclusive surfaces and asserted that no reconfiguration occured.
> 
> 
> (It's possible that this is more usefully _two_ tests)

These two tests sound like a better idea tho

2024-03-15 00:37 UTC, RAOF requested changes
Let's do some synchronous review of this next week. :wink:

2024-03-15 00:37 UTC, RAOF commented on tests/wlr_layer_shell_v1.cpp
> +        EXPECT_THAT(layer_surface.last_size().height, Eq(request_size.height));
I'm pretty sure this isn't testing what you expect it to be testing? Particularly: we've attached a buffer of size `initial_rect.size`. That means that the surface has size `initial_rect.size`; the client buffer size is authoritative.

What this is testing is that the WM has *suggested* (in the `configure` event) that we make the surface size `request_size.size`.

2024-03-18 20:52 UTC, RAOF approved these changes
Yeah, this is clearer now. Sweet!

2024-03-18 21:03 UTC, merged